name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trackup/frontend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint || echo "No lint script"
      - name: Build
        run: npm run build
      - name: Test
        run: npm test || echo "No test script"

  room-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trackup/room-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          if [ -f test.py ]; then python test.py; else echo "No tests"; fi

  user-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: trackup/user-service
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          if [ -f test.py ]; then python test.py; else echo "No tests"; fi
